print(dir("hello"))
print(help("hello".format))
s = "hello, my name is {}".format("Bogdan")
print(s)
s = "This contract is between lawyer {} and client {} and you will pay me {}$".format("Carlos", "Bogdan", "1thousand")
print(s)
print(s.count(" "))
print(s.lower())
print(s.split())

